name: Docker Deployment

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.USERNAME_TOCKEN }}
  DOCKER_PASSWORD: ${{ secrets.PASSWORD_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD


      - name: "Bulding Docker image"
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/srnzsystem .

      - name: "Pushing to Docker hub"
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/srnzsystem  








   
 

        
 